apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: kadiracr25.azurecr.io/microtodoui:latest  # Correct ACR image format
        ports:
        - containerPort: 80
        imagePullPolicy: Always  # Ensures the latest image is always pulled
      imagePullSecrets:
      - name: acr-secret  # Reference to the ACR secret
