apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default  # Change this if needed
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Change this if needed (must be between 30000-32767)
  type: LoadBalancer
